esphome:
  name: airbox
  platformio_options:
    board_build.f_cpu: 80000000L

esp8266:
  board: esp07

i2c:
  - id: bus_a
    sda: GPIO0  #D3
    scl: GPIO2  #D4 
    scan: True

# Enable logging
logger: 
  level: info

# Enable Home Assistant API
api:
  encryption:
    key: "TOfsRrJCtIp/9dy8yjqE9XkwbR81tHzxCQAajmeBZQI="

ota:
  password: "1547e8a15c61e76705c9fa0fd143165c"

wifi:
  fast_connect: True
  ssid: !secret wifi_ssid ## create your own secret.yaml file
  password: !secret wifi_password ## create your own secret.yaml file

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "airbox Fallback Hotspot"
    password: "buPthyk6mLkS"

captive_portal:
    
sensor:
  - platform: bme280
    temperature:
      name: "airbox BME280 Temperature"
      oversampling: 16x
      id: "airbox_temperature"
      unit_of_measurement: "°C"
      device_class: "temperature"
      accuracy_decimals: 1
      filters:
        - offset: -2.2 ## my sensor individual calibration
    pressure:
      name: "airbox BME280 Pressure"
      id: "airbox_pressure"
      unit_of_measurement: "hPa"
      device_class: "pressure"
      accuracy_decimals: 2
    humidity:
      name: "airbox BME280 Humidity"
      id: "airbox_humidity"
      unit_of_measurement: "%"
      device_class: "humidity"
      accuracy_decimals: 1
    iir_filter: 4x
    i2c_id: bus_a
    address: 0x76
    update_interval: 15s
  - platform: template
    name: "airbox BME280 Sea level pressure"
    id: "airbox_sea_level_pressure"
    update_interval: 15s
    unit_of_measurement: 'hPa'
    device_class: pressure
    accuracy_decimals: 2
    lambda: |-
      const float STANDARD_ALTITUDE = 500.0; // in meters
      return id(airbox_pressure).state / powf(1 - ((0.0065 * STANDARD_ALTITUDE) /
      (id(airbox_temperature).state + (0.0065 * STANDARD_ALTITUDE) + 273.15)), 5.257); // in hPa
    
  - platform: sps30
    pm_1_0:
      name: "airbox PM <1µm"  #Weight concentration
      id: "airbox_pm1"
      icon: "mdi:blur"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 1
    pm_2_5:
      name: "airbox PM <2.5µm"
      id: "airbox_pm2_5"
      icon: "mdi:blur"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 1
    pm_4_0:
      name: "airbox PM <4µm"
      id: "airbox_pm4"
      icon: "mdi:blur"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 1
    pm_10_0:
      name: "airbox PM <10µm"
      id: "airbox_pm10"
      icon: "mdi:blur"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 1

    pmc_0_5:
      name: "airbox NC <0.5µm" # Number concentration
      id: "airbox_nc0_5"
      icon: "mdi:blur-linear"
      unit_of_measurement: "#/cm³"
      accuracy_decimals: 1
    pmc_1_0:
      name: "airbox NC <1µm"
      id: "airbox_nc1"
      icon: "mdi:blur-linear"
      unit_of_measurement: "#/cm³"
      accuracy_decimals: 1
    pmc_2_5:
      name: "airbox NC <2.5µm"
      id: "airbox_nc2_5"
      icon: "mdi:blur-linear"
      unit_of_measurement: "#/cm³"
      accuracy_decimals: 1
    pmc_4_0:
      name: "airbox NC <4µm"
      id: "airbox_nc4"
      icon: "mdi:blur-linear"
      unit_of_measurement: "#/cm³"
      accuracy_decimals: 1
    pmc_10_0:
      name: "airbox NC <10µm"
      id: "airbox_nc10"
      icon: "mdi:blur-linear"
      unit_of_measurement: "#/cm³"
      accuracy_decimals: 1
    pm_size:
      name: "airbox Typical Particle size"
      id: "airbox_pm_size"
      unit_of_measurement: "µm"
      accuracy_decimals: 1
    address: 0x69
    update_interval: 15s

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi RSSI"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

web_server:
  port: 80
  
